edumap/urls.py
from django.urls import path

from . import views

app_name = "edumap"
urlpatterns = [
    path("", views.edumap, name="edumap"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh1", views.bangladesh, name="bangladesh1"),
    
]

map/urls.py
from django.urls import path

from . import views

app_name = "map"
urlpatterns = [
    path("", views.map, name="map"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh", views.bangladesh, name="bangladesh"),
    path("d3", views.d3, name="d3"),
    path("povertymap", views.povertymap, name="povertymap"),
    path("bdgeojson", views.bdgeojson, name="bdgeojson"),
    path("markermap", views.markermap, name="markermap"),
    path("mymarker", views.mymarker, name="mymarker"),
    path("mapSlider", views.mapSlider, name="mapSlider"),
    path("debug", views.debug, name="debug"),
]

edumap/models.py
from django.db import models

# Create your models here.

map/models.py
from django.db import models

# Create your models here.

edumap/views.py
from django.template import loader
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages


def edumap(request):
    template = loader.get_template('edumap/edumap.html')
    context = {}
    return HttpResponse(template.render(context, request))

def firstMap(request):
    template = loader.get_template('edumap/firstMap.html')
    context = {}
    return HttpResponse(template.render(context, request))

def bangladesh(request):
    template = loader.get_template('edumap/bangladesh.html')
    context = {}
    return HttpResponse(template.render(context, request))
def bangladesh0(request):
    template = loader.get_template('edumap/bangladesh0.html')
    context = {}
    return HttpResponse(template.render(context, request))

map/views.py
from django.template import loader
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages


def map(request):
    template = loader.get_template('map/map.html')
    context = {}
    return HttpResponse(template.render(context, request))

def firstMap(request):
    template = loader.get_template('map/firstMap.html')
    context = {}
    return HttpResponse(template.render(context, request))

def bangladesh(request):
    template = loader.get_template('map/bangladesh.html')
    context = {}
    return HttpResponse(template.render(context, request))

def bdgeojson(request):
    template = loader.get_template('map/bdgeojson.html')
    context = {}
    return HttpResponse(template.render(context, request))

def d3(request):
    template = loader.get_template('map/d3.html')
    context = {}
    return HttpResponse(template.render(context, request))

def povertymap(request):
    template = loader.get_template('map/povertymap.html')
    context = {}
    return HttpResponse(template.render(context, request))

def markermap(request):
    template = loader.get_template('map/markermap.html')
    context = {}
    return HttpResponse(template.render(context, request))

def mymarker(request):
    template = loader.get_template('map/mymarker.html')
    context = {}
    return HttpResponse(template.render(context, request))

def mapSlider(request):
    template = loader.get_template('map/mapSlider.html')
    context = {}
    return HttpResponse(template.render(context, request))

def debug(request):
    template = loader.get_template('map/debug.html')
    context = {}
    return HttpResponse(template.render(context, request))

edumap/templates/edumap/bangladesh.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'edumap/css/map.css' %}"/>
{% endblock pageStyle %}

{% block map %}

<div class="base">
  <svg id="svg_map"  viewBox="0 0 960 600"  xmlns="http://www.w3.org/2000/svg"
  preserveAspectRatio="xMidYMid meet"></svg>

  <div class="container pt-3">
    <div class="row flex space-around my-5" >
      <a href="#" id="prevStep" class="button round">&laquo;</a>
      <a href="#" id="prev" class="button round">&#8249;</a>
      <a href="#" id="next" class="button round">&#8250;</a>
      <a href="#" id="nextStep" class="button round">&raquo;</a>
    </div>
    <div class="row">
      <div class="col">
        <h4 >Map of Bangladesh</h4>
      </div>
      <div class="col">
        <label for="mySlider"
           style="display: inline-block; width: 240px; text-align: right">
           Radius = <span id="nRadius-value"> 10 </span>
        </label>
        <input type="range" name="mySlider" id=mySlider min="4" max="40" value="10">
      </div>
    </div>
  </div>
</div>

{% endblock map %}

{% block pageSpecificJavascript %}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js"></script> -->
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/topojson.v2.min.js"></script>

<script type="module">


var projection = d3.geoMercator().scale(4000).translate([-5850, 2000])

var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height")

var path = d3.geoPath().projection(projection);

var g = svg.append("g");
var g2=svg.append("g");
var g3=svg.append("g");
var g4=svg.append("g");
var g5=svg.append("g");
d3.queue()
    .defer(d3.json, "{% static  'edumap/json/bddistopo.json' %}")
    .defer(d3.json, "{% static  'edumap/json/gadm36_IND_1.json' %}")
    .defer(d3.json, "{% static  'edumap/json/gadm36_MMR_1.json' %}")
    .defer(d3.json, "{% static  'edumap/json/gadm36_BTN_1.json' %}")
    .defer(d3.json, "{% static  'edumap/json/gadm36_NPL_1.json' %}")
    .await(ready);

function ready(error, bangladesh,india,myanmar,bhutan,nepal) {
  console.log(bangladesh, india)

  g.selectAll("path")
				.data(topojson.feature(bangladesh, bangladesh.objects.bddis).features)
				.enter()
				.append("path")
				.attr("d", path)
        .attr("fill", "blue")
        .attr("stroke", "white")
        .attr("stroke-width", ".5px")
        .on("click", clicked)
        .append("title")
        .text(function(d) {return d.properties.NAME_2});

        g2.selectAll("path")
      				.data(topojson.feature(india, india.objects.gadm36_IND_1).features)
      				.enter()
      				.append("path")
      				.attr("d", path)
              .attr("fill", "green")
              .attr("hover", "red")
              .attr("stroke", "white")
              .attr("stroke-width", ".5px")
              .on("click", clicked)
              .append("title")
              .text(function(d) {return d.properties.NAME_2});
        g3.selectAll("path")
                    .data(topojson.feature(myanmar, myanmar.objects.gadm36_MMR_1).features)
                    .enter()
                    .append("path")
                    .attr("d", path)
                    .attr("fill", "yellow")
                    .attr("hover", "red")
                    .attr("stroke", "white")
                    .attr("stroke-width", ".5px")
                    .on("click", clicked)
                    ;

                    g4.selectAll("path")
                         .data(topojson.feature(bhutan, bhutan.objects.gadm36_BTN_1).features)
                         .enter()
                         .append("path")
                         .attr("d", path)
                         .attr("fill", "pink")
                         .attr("hover", "red")
                         .attr("stroke", "white")
                         .attr("stroke-width", ".5px")
                         .on("click", clicked);
                         g5.selectAll("path")
                               .data(topojson.feature(nepal, nepal.objects.gadm36_NPL_1).features)
                               .enter()
                               .append("path")
                               .attr("d", path)
                               //       .attr("fill", "lightblue")
                               .attr("fill", "blue")
                               .attr("hover", "red")
                               .attr("stroke", "white")
                               .attr("stroke-width", ".5px")
                               .on("click", clicked)

                               .append("title")
                               .text(function(d) {return d.properties.NAME_2});



  // g2.selectAll("path")
  //       .data(topojson.feature(india, india.objects.gadm36_IND_1).features)
  //       .enter()
  //       .append("path")
  //       .attr("d", path)
  //       .attr("stroke", "white")
  //       .attr("stroke-width", ".5px")
  //       .append("title")
  //       .text("Hello");

  newEvent(count)
}

// d3.json('https://raw.githubusercontent.com/techslides/D3-Maps/master/data/world/country/Bangladesh.topo.json', function(error, bangladesh) {
// d3.json('https://raw.githubusercontent.com/emon535/bangladesh-geojson/master/bangladesh.topo.json', function(error, bangladesh) {

var g6=svg.selectAll("g");
var popupData = [
{"event":"The First Event", "popupText":"The First PopUp", "lat":23.777176, "lon":90.399452},
{"event":"The Second Event", "popupText":"My location", "lat":23.983354, "lon":91.107775}
];



// var EventData = d3.json("{% static  'map/json/EventData.json' %}")
// console.log(popupData, EventData)

function rewrite(EventText){
svg.selectAll("text").remove()
svg.append('text').attr('y',-40).attr('x',-20).text("EVENT :")
svg.append('text').attr('y',-40).attr('x',-90).text(EventText)
}

function draw(d){
  console.log("draw called")
  rewrite(d.event)
  var text = d.popupText
  var x = projection([d.lon, d.lat])[0]
  var y = projection([d.lon, d.lat])[1]
  console.log(x,y)
  g6.selectAll("circle")

       .data([{"x":x, "y":y, "text":text}])
       .enter()
       .append("circle")
       .attr("cx", function(d) {return d.x})
       .attr("cy", function(d) {return d.y})
       .attr("r", 10)
       .style("fill", "red")
       .style("opacity", 0.6)
       .append('title')
       .text(function(d) {return d.text});

       g6.append("defs")

          .append("pattern")
          .attr("id", "bg")
          .attr("width", 1)
                .attr("height", 1)
                .attr("patternUnits", "objectBoundingBox")
               .append("image")

            		.attr("width", 15)
                .attr("height", 20)
           .attr("xlink:href", "http://lorempixel.com/200/200/")

       g6.selectAll("rect")
       .data([{"x":x-2, "y":y-35, "text":text}])
       .enter()
       .append("rect")
       .attr("x", function(d) {return d.x})
       .attr("y", function(d) {return d.y})
       .attr("width",5)
       .attr("height",20)
       .attr("fill", "url(#bg)")
       .text(function(d) {return d.text});

       var x1=x;
       var y1=y-10;
var y2=y1-15;
var y3=y1-15;
var x2=x+10;
var x3=x1-10;
console.log(x,y)
console.log(x1,y1)
console.log(x2,y2)
var points=x1  + ' ' + y1 + ', ' + x2 + ' ' + y2 + ', ' + x3 + ' ' + y3 ;


       g6.append("polyline")       // attach a polygon
         .style("stroke", "black")  // colour the line
         .style("fill", "black")     // remove any fill colour
         .attr("points", points);

}

function remove(){
  console.log("remove called")
  g6.selectAll("circle")
       .remove()
       g6.selectAll("rect")
       .remove()
       g6.selectAll("polyline")
       .remove()

}

let count = 0;

function newEvent(n){
  remove()
  draw(popupData[n])
}


// Listen to the next button
d3.select("#next").on("click", function(){
  if(count+1 < popupData.length){
    count++
    newEvent(count)
  }
  else{
    console.log("The last Event")
  }
})

// Listen to the prev button
d3.select("#prev").on("click", function(){
  if(count != 0){
    count--
    newEvent(count)
  }
  else{
    console.log("The first Event")
  }
})

// Listen to the prevStep button
d3.select("#prevStep").on("click", function(){
  if(count != 0){
    count--
    newEvent(count)
  }
})

// Listen to the nextStep button
d3.select("#nextStep").on("click", function(){
  if(count+1 < popupData.length){
    count++
    newEvent(count)
  }
})

// Listen to the slider
d3.select("#mySlider").on("change", function(d){
  d3.select("#nRadius-value").text(this.value)
  g6.selectAll("circle")
    .attr('r',this.value)


})

var centered

function clicked(d){
  console.log("District", d.properties.NAME_2, "data", d)
  var x = 0,
      y = 0;

  // If the click was on the centered state or the background, re-center.
  // Otherwise, center the clicked-on state.
  if (!d || centered === d) {
    centered = null;
  } else {
    var centroid = path.centroid(d);
    x = width / 2 - centroid[0];
    y = height / 2 - centroid[1];
    centered = d;
  }
  // Transition to the new transform.
  g6.transition()
      .duration(750)
      .attr("transform", "translate(" + x + "," + y + ")");
}
//zoom and pan functionality
var zoom= d3.zoom()
            .scaleExtent([0.8, 2])
            .on("zoom",function() { g6.attr("transform", d3.event.transform)})
svg.call(zoom)

</script>

{% endblock pageSpecificJavascript %}

edumap/templates/edumap/bdgeojson.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'map/css/map.css' %}"/>
{% endblock pageStyle %}

{% block map %}

<div class="base">
  <svg id="svg_map" width="960" height="600"></svg>
  <div class="container pt-3">
    <h4>Map of Bangladesh from GeoJson data</h4>
  </div>
</div>

{% endblock map %}

{% block pageSpecificJavascript %}
<script src="https://d3js.org/d3.v4.min.js"></script>

<script type="module">

var projection = d3.geoMercator().scale(4000).translate([-5850, 2000])

var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");

var path = d3.geoPath().projection(projection);

var g = svg.append("g");

d3.json("{% static  'map/json/bddis2.json' %}", function(error, bangladesh) {
  var geoPathGenerator = d3.geoPath().projection(projection);

  svg.append("path")
      .attr("d", geoPathGenerator(bangladesh))
      .attr("class", "feature")
      .attr("stroke", "white")
      .attr("stroke-width", "0.5px")
});

</script>
{% endblock pageSpecificJavascript %}

edumap/templates/edumap/d3.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'map/css/map.css' %}"/>
<script src="https://d3js.org/d3.v4.min.js"></script>
{% endblock pageStyle %}

{% block map %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="hello">
        Hello:
      </div>
      <ul id = "list">
         <li></li>
         <li></li>
      </ul>
    </div>
    <div class="col">
      <svg width="500" height="200" fill="yellow">
        <rect x = "100" y = "10" width = "300" height = "200" fill = "yellow"></rect>
        <line x1 = "100" y1 = "100" x2 = "200" y2 = "200" style = "stroke:rgb(155,0,0);stroke-width:2" />
      </svg>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="svgcontainer"></div>
    </div>
  </div>
</div>


{% endblock map %}

{% block pageSpecificJavascript %}
<script type="module">
  const message = d3.select("div.hello").html("Bye");
  d3.select("div.hello").classed("red", true)
  d3.select(".red").html("No red")

  d3.select("#list").selectAll("li")
    .data([10,20,30,40,50])
    .text(function(d) {return d})
    .enter()
    .append("li")
    .text(function(d) {return d})
    .attr("style", "color:red")

  var width = 300;
    var height = 300;
    //Create SVG element
    var svg = d3.select(".svgcontainer")
      .append("svg")
      .attr("width", width)
      .attr("height", height);
    //Append circle
    svg.append("circle")
      .attr("cx", 200)
      .attr("cy", 50)
      .attr("r", 300)
      .attr("fill", "green");
    svg.append("rect")
      .attr("x", 20)
      .attr("y", 20)
      .attr("width", 100)
      .attr("height", 100)
      .attr("fill", "yellow")
      .attr("transform", "translate(30, 30) rotate(45)")

    d3.select("body")
      .transition()
      .style("background-color", "gray")
      .duration(5000)
      .transition()
      .delay(5000)
      .style("background-color", "lightblue")
      .duration(5000)

</script>
{% endblock pageSpecificJavascript %}

edumap/templates/edumap/edumap.html
{% extends 'base.html' %}
{% load static %}

{% block spadof %} {% endblock %}

{% block navbar %}
	{% include 'navbar4.html' %}
{% endblock %}

{% block later %}

<!-- categories section -->
	<section class="categories-section spad">
		<div class="container">
			<div class="section-title">
				<h2>Our Maps</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
			</div>
			<div class="row">
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/1.jpg' %}"></div>
						<div class="ci-text">
              <a href="{% url 'edumap:firstMap' %}">
                <h5>First Map</h5>
              </a>
							<p>First Map</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
			</div>
		</div>
	</section>
	<!-- categories section end -->
{% endblock later %}

edumap/templates/edumap/firstMap.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block css %}{% endblock css %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'edumap/css/map.css' %}"/>



{% endblock pageStyle %}

{% block map %}
<content id="content"></content>
{% endblock map %}

{% block javascript %}{% endblock javascript %}
{% block pageSpecificJavascript %}
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/topojson.v2.min.js"></script>

<script type="module">

var width = window.innerWidth, height = window.innerHeight;
var projection = d3.geoNaturalEarth1()
  .rotate([10,0])
   .center([width/13.2, width/52.8]) //long and lat starting position
  .scale(width/0.25) //starting zoom position

var svg = d3.select("body").append("svg")
                          .attr("width", width)
                          .attr("height", height)
                          // .attr("preserveAspectRatio", "xMinYMin meet")
                          // .attr("viewBox", "0 0 width height")

var path = d3.geoPath()
  .projection(projection);

console.log(window.innerHeight)

var g = svg.append("g");

d3.json('https://raw.githubusercontent.com/techslides/D3-Maps/master/data/world/country/Bangladesh.topo.json', function(error, topology) {

  var world = g.selectAll("path")
				.data(topojson.feature(topology, topology.objects.map).features)
        .enter()
        .append("path")
        .attr("d", path);



});



// d3.json('https://unpkg.com/world-atlas@1.1.4/world/110m.json')
//   .then(data => {
//     const countries = feature(data, data.objects.countries);
//     svg.selectAll('path').data(countries.features)
//       .enter().append('path')
//         .attr('class', 'country')
//         .attr('d', pathGenerator);
// });

</script>
{% endblock pageSpecificJavascript %}

edumap/templates/edumap/firstMap0.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'map/css/map.css' %}"/>
{% endblock pageStyle %}

{% block map %}

<div class="base">
  <svg id="svg_map" width="960" height="600"></svg>
  <div class="container pt-3">
    <h4>World Map Showing data with Legend</h4>
  </div>
</div>

{% endblock map %}

{% block pageSpecificJavascript %}
<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
<script src="https://d3js.org/d3-geo-projection.v2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3-legend/2.24.0/d3-legend.js"></script>
<script src="https://d3js.org/d3-scale-chromatic.v1.min.js"></script>
<!-- <script src="https://d3js.org/topojson.v2.min.js"></script>
<script src="https://unpkg.com/d3-simple-slider"></script> -->

<script type="module">
// The svg
var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");

// Map and projection
var projection = d3.geoNaturalEarth()
    .scale(width / 2 / Math.PI)
    .translate([width / 2, height / 2])
var path = d3.geoPath()
    .projection(projection);

// Data and color scale
var data = d3.map();
var colorScheme = d3.schemeReds[6];
colorScheme.unshift("#eee")
var colorScale = d3.scaleThreshold()
    .domain([1, 6, 11, 26, 101, 1001])
    .range(colorScheme);

// Legend
var g = svg.append("g")
    .attr("class", "legendThreshold")
    .attr("transform", "translate(20,20)");
g.append("text")
    .attr("class", "caption")
    .attr("x", 0)
    .attr("y", -6)
    .text("Students");
var labels = ['0', '1-5', '6-10', '11-25', '26-100', '101-1000', '> 1000'];
var legend = d3.legendColor()
    .labels(function (d) { return labels[d.i]; })
    .shapePadding(4)
    .scale(colorScale);
svg.select(".legendThreshold")
    .call(legend);

// Load external data and boot
d3.queue()
    .defer(d3.json, "http://enjalot.github.io/wwsd/data/world/world-110m.geojson")
    .defer(d3.csv, "{% static 'map/csv/data.csv' %}", function(d) { data.set(d.code, +d.total); })
    .await(ready);

function ready(error, topo) {
    if (error) throw error;

    // Draw the map
    svg.append("g")
        .attr("class", "countries")
        .selectAll("path")
        .data(topo.features)
        .enter()
        .append("path")
        .attr("fill", function (d){
          // Pull data for this country
          d.total = data.get(d.id) || 0;
          // Set the color
          return colorScale(d.total);
        })
        .attr("d", path);
}

svg.call(d3.zoom().on('zoom',()=>{
	console.log("Zooming..")
  g.attr('transform', d3.event.transform)
}))

</script>
{% endblock pageSpecificJavascript %}

edumap/templates/edumap/map.html
{% extends 'base.html' %}
{% load static %}

{% block spadof %} {% endblock %}

{% block navbar %}
	{% include 'navbar4.html' %}
{% endblock %}

{% block later %}

<!-- categories section -->
	<section class="categories-section spad">
		<div class="container">
			<div class="section-title">
				<h2>Our Maps</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
			</div>
			<div class="row">
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/1.jpg' %}"></div>
						<div class="ci-text">
              <a href="{% url 'map:firstMap' %}">
                <h5>First Map</h5>
              </a>
							<p>First Map</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/2.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:bangladesh' %}">
								<h5>bangladesh Map</h5>
							</a>
							<p>bangladesh Map</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/3.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:d3' %}">
								<h5>Various D3</h5>
							</a>
							<p>Various D3</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/4.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:povertymap' %}">
								<h5>Poverty Map</h5>
							</a>
							<p>Map of Bangladesh with poverty data</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/4.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:bdgeojson' %}">
								<h5>BD GeoJson</h5>
							</a>
							<p>Map of Bangladesh with GeoJson data</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/4.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:markermap' %}">
								<h5>Map of BANGLADESH with many THing</h5>
							</a>
							<p>World Map with Circle Marker</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/4.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:mymarker' %}">
								<h5>World Map with Marker</h5>
							</a>
							<p>World Map with Marker</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
			</div>
		</div>
	</section>
	<!-- categories section end -->
{% endblock later %}

edumap/templates/edumap/markermap.html
{% extends 'abstractbase.html' %}
{% load static %}
{% block pageStyle %}
<link rel="stylesheet" href="{% static 'map/css/map.css' %}"/>
{% endblock pageStyle %}

{% block map %}

<div class="base">
  <svg id="svg_map" width="960" height="600"></svg>
  <div class="container pt-3">
    <h4>Map of World with Marker</h4>
  </div>
</div>

{% endblock map %}

{% block pageSpecificJavascript %}

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="https://d3js.org/topojson.v2.min.js"></script>
<script>

var projection = d3.geoMercator().scale(4000).translate([-5850, 2000])

var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");

var path = d3.geoPath().projection(projection);

var g = svg.append("g");

d3.json("{% static  'map/json/bddistopo.json' %}", function(error, bangladesh) {

  var bangladesh = g.selectAll("path")
				.data(topojson.feature(bangladesh, bangladesh.objects.bddis).features)
				.enter()
				.append("path")
				.attr("d", path)
        .attr("fill", "green")
        .attr("stroke", "white")
        .attr("stroke-width", ".5px")


var popupData = [
  {"code":"DHA", "city":"DHAKA", "country":"BANGLADESH", "lat":23.777176, "lon":90.399452}
];

function draw(d){
  console.log(d)
  var x = projection([d.lon, d.lat])[0]
  var y = projection([d.lon, d.lat])[1]
  console.log(x,y)
  g.selectAll("circle")
       .data([{"x":x, "y":y}])
       .enter()
       .append("circle")
       .attr("cx", function(d) {return d.x})
       .attr("cy", function(d) {return d.y})
       .attr("r", 5)
       .style("fill", "red")
       .style("opacity", 0.6)
}

draw(popupData[0])

})
  //zoom and pan functionality
  var zoom = d3.zoom().on("zoom",function() {
    g.attr("transform", d3.event.transform)
  });
  svg.call(zoom);

</script>

{% endblock pageSpecificJavascript %}