arrijal/users/urls.py
from django.urls import path

from arrijal.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.blogpage, name="blog"),
    path('category-dao/<category_id>/', views.category_dao, name='category-dao'),
    path("search/", views.search, name="search"),

    #path("delete/<int:id>/", views.delete, name="delete"),
    #path("edit/<int:id>/", views.edit, name="edit"),
    #path("readmore/<int:id>/", views.readmore, name="readmore"),
]

edumap/urls.py
from django.urls import path

from . import views

app_name = "edumap"
urlpatterns = [
    path("", views.edumap, name="edumap"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh1", views.bangladesh, name="bangladesh1"),
    
]

isnad/urls.py
from django.urls import path

from . import views

app_name = "isnad"
urlpatterns = [
    path("", views.isnad, name="isnad"),
    path("sgraph", views.sgraph, name="sgraph"),
    path("igraph", views.igraph, name="igraph"),
    path("graph1", views.graph1, name="graph1"),
    path("graph2", views.graph2, name="graph2"),
    path("graph3", views.graph3, name="graph3"),
    path("graph4", views.graph4, name="graph4"),
    path("graph5", views.graph5, name="graph5"),

    path("sload", views.sload, name="sload"),
    path("iload", views.iload, name="iload"),

    path("getrawisload", views.getrawisload, name="getrawisload"),


]

map/urls.py
from django.urls import path

from . import views

app_name = "map"
urlpatterns = [
    path("", views.map, name="map"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh", views.bangladesh, name="bangladesh"),
    path("d3", views.d3, name="d3"),
    path("povertymap", views.povertymap, name="povertymap"),
    path("bdgeojson", views.bdgeojson, name="bdgeojson"),
    path("markermap", views.markermap, name="markermap"),
    path("mymarker", views.mymarker, name="mymarker"),
    path("mapSlider", views.mapSlider, name="mapSlider"),
    path("debug", views.debug, name="debug"),
]

three/urls.py
from django.urls import path

from . import views

app_name = "three"
urlpatterns = [
    path("", views.three, name="three"),
    path("equations", views.equations, name="equations"),
    path("experiment", views.experiment, name="experiment"),
    path("aromaticChart", views.aromaticChart, name="aromaticChart"),
    path("aliphaticChart", views.aliphaticChart, name="aliphaticChart"),
    path("tankofnet", views.tankofnet, name="tankofnet"),
    path("tank", views.tank, name="experimentTank"),
    path("guiexample", views.guiexample, name="guiexample"),
    path("base", views.base, name="base"),
    path("periodic", views.periodic, name="periodic"),
    path("alcohol", views.alcohol, name="alcohol"),
    path("molecules", views.molecules, name="molecules"),
    path("desmos", views.desmos, name="desmos"),
]

arrijal/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

arrijal/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

arrijal/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

arrijal/templates/abstractbase.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}ArRijal{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Educational Website">
    <meta name="keywords" content="arrijal, education, creative, html">
    <meta name="author" content="Zihan et al">


    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <!-- <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}"> -->
    <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/apple-touch-icon.png' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-32x32.png' %}"/>
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/favicon-16x16.png' %}"/>

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <!-- Owl carousel 2.2.1 -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.carousel.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/assets/owl.carousel.css" integrity="sha256-h7NPLBxMMPcEeO/BDGwCb5MRAZ8CgVcxRxfm3fpMH0s=" crossorigin="anonymous" />
    <!-- Font awesome -->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <!-- Google Fonts -->
    <!-- Google Fonts -->
  	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

    {% endblock %}
    {% block pageSpecificCSS %} {% endblock pageSpecificCSS %}
    {% block pageStyle %} {% endblock pageStyle %}
  </head>

  <body>

  {% block base %}
  {% endblock base %}

  {% block animation %}
  {% endblock animation %}

  {% block map %}
  {% endblock map %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      <!-- font awesome -->
      <!-- <script src="https://use.fontawesome.com/a42fb6a986.js"></script> -->
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.svg"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.eot"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/fonts/fontawesome-webfont.woff2"></script> -->
      <!-- font awesome end -->

      <!-- Owl carousel -->
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js"></script> -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.2.1/owl.carousel.min.js" integrity="sha256-s5TTOyp+xlSmsDfr/aZhg0Gz+JejYr5iTJI8JxG1SkM=" crossorigin="anonymous"></script>
      <!-- jquery-circle-progress -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-circle-progress/1.2.2/circle-progress.min.js" integrity="sha256-2XpjfLL5tRYLa3AAM0gz6aAY0zxvHogDzTWemxkTPDg=" crossorigin="anonymous"></script>
      <!-- jquery  -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
      <!-- Mix it up -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/mixitup/3.3.0/mixitup.min.js" integrity="sha256-zg8soQ/ZV530IpNYcUnPrbHZvilKTK8PSoHOVusa2uY=" crossorigin="anonymous"></script>

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>

    {% endblock javascript %}
    {% block pageSpecificJavascript %} {% endblock pageSpecificJavascript %}
  </body>
</html>

arrijal/templates/base.html
{% extends "abstractbase.html" %}
{% load static i18n %}

{% block base %}

      <!-- Header section -->
      <header class="header-section">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-3">
              <div class="site-logo">
                <a href="{% url 'home' %}">
                  <img src="{% static 'img/logo.png' %}" alt="">
                </a>
              </div>
              <div class="nav-switch">
                <i class="fa fa-bars"></i>
              </div>
            </div>
            <div class="col-lg-9 col-md-9">
              <nav class="main-menu">
                <ul>
                  <li><a href="{% url 'home' %}">Home</a></li>
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'users:detail' request.user.username %}">Profile</a></li>
                  {% endif %}
                  <li><a href="{% url 'three:three' %}">Animation</a></li>
                  <li><a href="{% url 'map:map' %}">Maps</a></li>
                    <li><a href="{% url 'blog:blog' %}">Blogs</a></li>
                  {% if user.is_authenticated %}
                    <li><a href="{% url 'account_logout' %}" class="site-btn header-btn pb-3">LogOut</a></li>
                  {% else %}
                    <li><a href="{% url 'account_login' %}" class="site-btn header-btn pb-3">Login</a></li>
                  {% endif %}
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </header>
      <!-- Header section end -->

    {% block navbar %}
      {% include 'navbar2.html' %}
    {% endblock %}

    <div class="container">
    {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
      {% endfor %}
    {% endif %}

    {% block spadof %}
    <section class="spad">
      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </section>
    {% endblock spadof %}
    </div> <!-- /container -->

    {% block later %}{% endblock later %}

    {% block modal %}{% endblock modal %}

    {% if not user.is_authenticated %}
      {% block registerNow %}
      <!-- banner section -->
      <section class="banner-section spad">
      	<div class="container">
      		<div class="section-title mb-0 pb-2">
      			<h2>Join ArRijal Community Now!</h2>
      			<p>We will send you mail on update of our work. (Which you can unsubscribe at any time.)
              You can give us your much appreciated advice or send us ur good will at our
              <a href="{% url 'review:review' %}">review page</a>.
            </p>
      		</div>
      		<div class="text-center pt-5">
      			<a href="{% url 'account_signup' %}" class="site-btn">Register Now</a>
      		</div>
      	</div>
      </section>
      <!-- banner section end -->
      {% endblock %}
    {% endif %}

    {% include 'footer.html' %}


{% endblock %}

arrijal/templates/footer.html
{% load static i18n %}

<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Contact Info</h4>
						<ul class="contact-list">
							<li>Sadar, Branhmanbaria, BD <br> and We have many friends<br> working with us</li>
							<li>+880 1680 110838</li>
							<li>mizihan84@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Animation</h4>
						<ul>
							<li><a href="{% url 'isnad:isnad' %}">Isnad Tree</a></li>
							<li><a href="{% url 'chemistry:chemistry' %}">HSC Chemistry</a></li>
							<li><a href="{% url 'edumap:edumap' %}">Map for Education</a></li>
							<li><a href="{% url 'physics:physics' %}">Physics</a></li>
							<li><a href="">SSC Physics(Coming Soon)</a></li>
							<li><a href="">For others Class(Coming Soon)</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Cheer US <br> EVERYWHERE!!!</h4>
						<ul>
							<li>
								<span class="site-breadcrumb"> <a href=""> <i class="fa fa-github"></i> .......Ar Rijal</a></span>
							</li>
							<li>
								<span class="site-breadcrumb"> <a href=""> <i class="fa fa-facebook"></i> ........Ar Rijal</a></span>
							</li>
							<li>
								<span class="site-breadcrumb"> <a href=""> <i class="fa fa-youtube"></i> .......Ar Rijal</a></span>
							</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Give us a Review</h4>
						<ul>
							<li> <p>Tell us how we are <br>
								 		doing and please mention <br>
										our lackings and weakness <br>
										in your eyes </p> </li>
							<li>
								<span class="site-breadcrumb">
									<a href="{% url 'review:review' %}">Review Page</a>
								</span>
							</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Newsletter</h4>
						<form class="footer-newslatter" method="post" action="{% url 'newsletter:subscribe' %}">
							{% csrf_token %}
							<input type="email" name="email" placeholder="E-mail">
							<button class="site-btn">Subscribe</button>
							<p>*We don’t spam</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Register</a></li>
					<li><a href="#">Privacy</a></li>
				</ul>
				<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->

arrijal/templates/navbar.html
{% load static i18n %}

<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'img/bg.jpg' %}">
  <div class="container">
    <div class="hero-text text-white">
      <h2><b>ArRijal</b>, a man <em>Against</em> the <em>Tide</em> </h2>
      <p>Our humble attempt to create such man of valor and courage to stand against the massive
        and vile <em>Tides</em> in the world, to stop it in its track and create a heroic reverse
        tide of clarity, equality, a tide against hunger, oppressions and much more with the help
        of knowledge.</p>
    </div>
    <!-- TODO: Add a search bar here by modifying it -->
    <!-- <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form class="intro-newslatter">
          <input type="text" placeholder="Name">
          <input type="text" class="last-s" placeholder="E-mail">
          <button class="site-btn">Sign Up Now</button>
        </form>
      </div>
    </div> -->
  </div>
</section>
<!-- Hero section end -->

arrijal/templates/navbar2.html
{% load static i18n %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'img/page-bg/2.jpg' %}">
	<div class="container">
		<div class="site-breadcrumb">
			<a href="{% url 'home' %}">Home</a>
			<span>Accounts</span>
		</div>
	</div>
</div>
<!-- Page info end -->

arrijal/templates/navbar3.html
{% load static i18n %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'img/page-bg/3.jpg' %}">
  <div class="container">
		<div class="site-breadcrumb">
			<a href="{% url 'home' %}">Home</a>
			<span>Animation</span>
		</div>
	</div>
</div>
<!-- Page info end -->

arrijal/templates/navbar4.html
{% load static i18n %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'img/page-bg/4.jpg' %}">
  <div class="container">
		<div class="site-breadcrumb">
			<a href="{% url 'home' %}">Home</a>
			<span>Maps</span>
		</div>
	</div>
</div>
<!-- Page info end -->

arrijal/templates/navbar5.html
{% load static i18n %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'img/page-bg/5.jpg' %}">
	<div class="container">
		<div class="site-breadcrumb">
			<a href="{% url 'home' %}">Home</a>
			<span>Blogs</span>
		</div>
	</div>
</div>
<!-- Page info end -->