arrijal/users/urls.py
from django.urls import path

from arrijal.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

chemistry/urls.py
from django.urls import path

from . import views

app_name = "chemistry"
urlpatterns = [
    path("", views.chemistry, name="chemistry"),
    path("tank", views.tank, name="tank"),
    path("oxygen", views.oxygen, name="oxygen"),
    path("molecule", views.molecule, name="molecule"),
    path("raycaster", views.raycaster, name="raycaster"),


]

isnad/urls.py
from django.urls import path

from . import views

app_name = "isnad"
urlpatterns = [
    path("", views.isnad, name="isnad"),
    path("sgraph", views.sgraph, name="sgraph"),
    path("igraph", views.igraph, name="igraph"),
    path("graph1", views.graph1, name="graph1"),
    path("graph2", views.graph2, name="graph2"),
    path("graph3", views.graph3, name="graph3"),
    path("graph4", views.graph4, name="graph4"),
    path("graph5", views.graph5, name="graph5"),

    path("sload", views.sload, name="sload"),
    path("iload", views.iload, name="iload"),

    path("getrawisload", views.getrawisload, name="getrawisload"),


]

map/urls.py
from django.urls import path

from . import views

app_name = "map"
urlpatterns = [
    path("", views.map, name="map"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh", views.bangladesh, name="bangladesh"),
    path("d3", views.d3, name="d3"),
    path("povertymap", views.povertymap, name="povertymap"),
    path("bdgeojson", views.bdgeojson, name="bdgeojson"),
    path("markermap", views.markermap, name="markermap"),
    path("mymarker", views.mymarker, name="mymarker"),
    path("mapSlider", views.mapSlider, name="mapSlider"),
    path("debug", views.debug, name="debug"),
]

physics/urls.py
from django.urls import path

from . import views

app_name = "physics"
urlpatterns = [
    path("", views.physics, name="physics"),
    path("firstGame/", views.firstGame, name="firstGame"),
    path("mod2d/", views.mod2d, name="mod2d"),
    path("threed/", views.threed, name="threed"),
    path("threed_mobile/", views.threed_mobile, name="threed_mobile"),
]

three/urls.py
from django.urls import path

from . import views

app_name = "three"
urlpatterns = [
    path("", views.three, name="three"),
    path("equations", views.equations, name="equations"),
    path("experiment", views.experiment, name="experiment"),
    path("aromaticChart", views.aromaticChart, name="aromaticChart"),
    path("aliphaticChart", views.aliphaticChart, name="aliphaticChart"),
    path("tankofnet", views.tankofnet, name="tankofnet"),
    path("tank", views.tank, name="experimentTank"),
    path("guiexample", views.guiexample, name="guiexample"),
    path("base", views.base, name="base"),
    path("periodic", views.periodic, name="periodic"),
    path("alcohol", views.alcohol, name="alcohol"),
    path("molecules", views.molecules, name="molecules"),
    path("desmos", views.desmos, name="desmos"),
]

arrijal/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

home/models.py
from django.db import models

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel


class HomePage(Page):
    body = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
    ]

arrijal/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

arrijal/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

arrijal/templates/pages/about.html
{% extends "base.html" %}

arrijal/templates/pages/home.html
{% extends "base.html" %}
{% load static %}

{% block spadof %} {% endblock %}

{% block navbar %}
  {% include 'navbar.html' %}
{% endblock %}

{% block later %}

  <!-- course section -->
	<section class="course-section spad">
    <div class="course-warp">
      <div class="container">
        <div class="section-title">
          <h2>Our Featured Works</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec malesuada lorem maximus mauris scelerisque, at rutrum nulla dictum. Ut ac ligula sapien. Suspendisse cursus faucibus finibus.</p>
        </div>
      </div>
			<ul class="course-filter controls pt-1">
				<li class="control active" data-filter="all">All</li>
        <li class="control" data-filter=".isnad">Isnad</li>
				<li class="control" data-filter=".chemistry">Chemistry</li>
        <li class="control" data-filter=".physics">Physics</li>
        <li class="control" data-filter=".map">Maps</li>
				<li class="control" data-filter=".animation">Animations</li>
			</ul>
			<div class="row course-items-area">
<!-- .................... isnad   ............................. -->
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 isnad">
          <div class="categorie-item">
            <div class="ci-thumb set-bg" data-setbg="{% static 'isnad/img/scholar.jpeg' %}"></div>
            <div class="ci-text">
              <a href="{% url 'isnad:igraph' %}">
                <h5> السند  </h5>
              </a>
              <p> Hadith text, translation  and interactive chain of narrators (isnad)  </p>
              <span>The chain of narration</span>
            </div>
          </div>
        </div>
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 full isnad">
          <div class="categorie-item">
            <div class="ci-thumb set-bg" data-setbg="{% static 'isnad/img/scholar.jpeg' %}"></div>
            <div class="ci-text">
              <a href="{% url 'isnad:sgraph' %}">
                <h5>  علماء المسلمين   </h5>
              </a>
              <p> Authentic Inter-linked graph of Muslim Scholars </p>
              <span>Muslim Scholars</span>
            </div>
          </div>
        </div>
        <!-- categorie -->
<!-- .................... chemistry   ............................. -->
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'three/img/aliphatic-1.jpeg' %}"></div>
						<div class="ci-text">
              <a href="{% url 'three:aliphaticChart' %}">
                <h5>Aliphatic Chart</h5>
              </a>
							<p>Aliphatic Chart</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'three/img/aromatic-1.png' %}"></div>
						<div class="ci-text">
							<a href="{% url 'three:aromaticChart' %}">
								<h5>Aromatic Chart</h5>
							</a>
							<p>Aromatic Chart</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'three/img/PeriodicTable-2.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'three:periodic' %}">
								<h5>Periodic Table</h5>
							</a>
							<p>Periodic Table in many shape !!!</p>
							<span>Size: No siZe</span>
						</div>
					</div>
				</div>
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'chemistry/img/molecule-1.jpeg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'chemistry:molecule' %}">
								<h5>Molecules</h5>
							</a>
							<p>C</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'three/img/formula-2.jpeg' %}"></div>
						<div class="ci-text">
              <a href="{% url 'three:equations' %}">
                <h5>Chemistry Equation</h5>
              </a>
							<p>Chemistry Equation Dummy</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 chemistry">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'three/img/PlotingEquation-1.jpeg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'three:desmos' %}">
								<h5>Ploting Equation</h5>
							</a>
							<p>Ploting Mathmatical Equation on Graph</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
<!-- .................... physics   ............................. -->
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 physics">
          <div class="categorie-item">
            <div class="ci-thumb set-bg" data-setbg="{% static 'physics/img/game-1.png' %}"></div>
            <div class="ci-text">
              <a href="{% url 'physics:threed' %}">
                <h5>3d Game</h5>
              </a>
              <p>A Basic 3d Game of Unity</p>
              <span>Size: No</span>
            </div>
          </div>
        </div>
        <!-- categorie -->
<!-- .................... map   ............................. -->
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 map">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static '/map/img/world-2.jpeg' %}"></div>
						<div class="ci-text">
              <a href="{% url 'map:firstMap' %}">
                <h5>First Map</h5>
              </a>
							<p>First Map</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 map">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static '/map/img/bd-2.jpeg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:povertymap' %}">
								<h5>Poverty Map</h5>
							</a>
							<p>Map of Bangladesh with poverty data</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 map">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static '/map/img/bd-1.png' %}"></div>
						<div class="ci-text">
							<a href="{% url 'map:mapSlider' %}">
								<h5>Map with Slider</h5>
							</a>
							<p>Map with Slider</p>
							<span>Size: No</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
<!-- .................... animation   ............................. -->
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 animation">
          <div class="categorie-item">
            <div class="ci-thumb set-bg" data-setbg="{% static 'three/img/tank-1.png' %}"></div>
            <div class="ci-text">
              <a href="{% url 'three:experimentTank' %}">
                <h5>A Small Park</h5>
              </a>
              <p>Experimenting on the scenegraph.</p>
              <span>Size: Unknown</span>
            </div>
          </div>
        </div>
        <!-- categorie -->
        <div class="mix col-lg-3 col-md-4 col-sm-6 animation">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static '/chemistry/img/helicopter-3.png' %}"></div>
						<div class="ci-text">
							<a href="{% url 'chemistry:tank' %}">
								<h5>Helicopter</h5>
							</a>
							<p>A Helicopter is playing by itself...</p>
							<span>Size: bad de pm</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
<!-- ....................     ............................. -->


			</div>
		</div>
	</section>
	<!-- course section end -->


  {% if user.is_authenticated %}
    <section class="spad"></section>
  {% endif %}

{% endblock later %}