isnad/urls.py
from django.urls import path

from . import views

app_name = "isnad"
urlpatterns = [
    path("", views.isnad, name="isnad"),
    path("sgraph", views.sgraph, name="sgraph"),
    path("igraph", views.igraph, name="igraph"),
    path("graph1", views.graph1, name="graph1"),
    path("graph2", views.graph2, name="graph2"),
    path("graph3", views.graph3, name="graph3"),
    path("graph4", views.graph4, name="graph4"),
    path("graph5", views.graph5, name="graph5"),

    path("sload", views.sload, name="sload"),
    path("iload", views.iload, name="iload"),

    path("getrawisload", views.getrawisload, name="getrawisload"),


]

map/urls.py
from django.urls import path

from . import views

app_name = "map"
urlpatterns = [
    path("", views.map, name="map"),
    path("firstMap", views.firstMap, name="firstMap"),
    path("bangladesh", views.bangladesh, name="bangladesh"),
    path("d3", views.d3, name="d3"),
    path("povertymap", views.povertymap, name="povertymap"),
    path("bdgeojson", views.bdgeojson, name="bdgeojson"),
    path("markermap", views.markermap, name="markermap"),
    path("mymarker", views.mymarker, name="mymarker"),
    path("mapSlider", views.mapSlider, name="mapSlider"),
    path("debug", views.debug, name="debug"),
]

isnad/models.py
from django.db import models

# Create your models here.

isnad/views.py
from django.template import loader
from django.shortcuts import render
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import redirect
import json

def isnad(request):
    template = loader.get_template('isnad/isnad.html')
    context = {}
    return HttpResponse(template.render(context, request))

def sgraph(request):
    template = loader.get_template('isnad/sgraph.html')
    context = {}
    return HttpResponse(template.render(context, request))

def igraph(request):
    template = loader.get_template('isnad/igraph.html')
    context = {}
    return HttpResponse(template.render(context, request))

def graph1(request):
    template = loader.get_template('isnad/graph1.html')
    context = {}
    return HttpResponse(template.render(context, request))

def graph2(request):
    template = loader.get_template('isnad/graph2.html')
    context = {}
    return HttpResponse(template.render(context, request))

def graph3(request):
    template = loader.get_template('isnad/graph3.html')
    context = {}
    return HttpResponse(template.render(context, request))

def graph4(request):
    template = loader.get_template('isnad/graph4.html')
    context = {}
    return HttpResponse(template.render(context, request))

def graph5(request):
    template = loader.get_template('isnad/graph5.html')
    context = {}
    return HttpResponse(template.render(context, request))


def sload(request):
    start=0;
    end=40023;
    wdata = {}
    wdata['nodes'] = []
    wdata['links'] = []
    with open('isnad/static/isnad/datasets/all_rawis_smt.json') as json_file:
        ldata = json.load(json_file)
    with open('isnad/static/isnad/datasets/all_rawis.json') as json_file:
        aldata = json.load(json_file)
    for a in aldata['info']:
        if start <= a['scholar_indx'] <= end:
            wdata['nodes'].append({
                'id': a['scholar_indx'],
                'name':a['name'],
                'group':a['grade']
            })
    for index,l in enumerate(ldata['links']):
        for t in l['target']:
            if not (str(t)) == "NA":
                if start <= t <= end and start <= l['source'] <= end:
                    wdata['links'].append({
                        'source': l['source'],
                        'target': t,
                    })
    with open('isnad/static/isnad/datasets/some_rawis.json', 'w') as outfile:
        json.dump(wdata, outfile)
    return redirect('isnad:isnad')


def iload(request):
    name=""
    start=0
    end=34442
    j=0
    all="hadiths"
    source=""
    chapter=""
    rawis=[]
    dic={}
    wdata = {}
    wdata['nodes'] = []
    wdata['links'] = []

    with open('isnad/static/isnad/datasets/all_hadiths_clean.json') as json_file:
        aldata = json.load(json_file)
    with open('isnad/static/isnad/datasets/all_hadiths_chain.json') as json_file:
        cdata = json.load(json_file)
    with open('isnad/static/isnad/datasets/all_rawis.json') as json_file:
        rdata = json.load(json_file)
    with open('isnad/static/isnad/datasets/getrawisindex.json') as json_file:
        getindex = json.load(json_file)

    wdata['nodes'].append({
        'id': all,
        'group':all,
        'level':1,
        'book':'all'
    })

    for index,a in enumerate(aldata['info']):
        if start <= index <= end:
            wdata['nodes'].append({
                'id': index,
                'name': a['hadith_no'],
                'group': "hadith",
                'level': 4,
                'text': a['text_en'],
                'hadith_no': a['hadith_no'].strip(),
                'book': a['source'].strip(),
                'chain_indx': a['chain_indx'].replace(" ", "").split(",")
            })
            if a['hadith_no'] == " 1 ":
                source = aldata['info'][index]['source']
                wdata['nodes'].append({
                    'id': a['source'],
                    'name':a['source'],
                    'group': "source",
                    'level':2,
                    'book':a['source'].strip()
                })
                wdata['links'].append({
                    'source': all ,
                    'target': a['source'],
                    'book':a['source'].strip()

                })
            if a['id'] == 0:
                chapter = aldata['info'][index]['chapter']
                print(chapter)
                wdata['nodes'].append({
                    'id': a['chapter'],
                    'name':a['chapter'],
                    'group':"chapter",
                    'level':3,
                    'chapter':a['chapter'],
                    'book':a['source'].strip()
                })
            wdata['links'].append({
                'source': source ,
                'target': chapter,
                'chapter':a['chapter'],
                'book':a['source'].strip()

            })
            wdata['links'].append({
                'source': chapter ,
                'target': index,
                'hadith_no':a['hadith_no'].strip(),
                'book':a['source'].strip(),
                'level':4
            })

    for index,c in enumerate(cdata['info']):
        j=0
        if  start <= index <= end:
            hadith_id = index
            for s in c['chain_indx']:
                if str(c['chain_indx'][j]) not in rawis:
                    rawis.append(str(cdata['info'][index]['chain_indx'][j]))
                    name=str(c['chain_indx'][j])
                    if str(cdata['info'][index]['chain_indx'][j]) in getindex:
                        name = rdata['info'][getindex[str(cdata['info'][index]['chain_indx'][j])]]['name']
                    wdata['nodes'].append({
                        'id': str(c['chain_indx'][j]),
                        'name':name,
                        'group':"rawis",
                        'level':5,
                        'list':list(aldata['info'][index]['hadith_no'].strip().split(" "))
                    })
                    #dic.add(len(rawis)-1, len(wdata['nodes'])-1)
                    dic[len(rawis)-1]=len(wdata['nodes'])-1
                else:
                    p=rawis.index(str(c['chain_indx'][j]))
                    k=dic[p]
                    wdata['nodes'][k]['list'].append(aldata['info'][index]['hadith_no'].strip())


                wdata['links'].append({
                    'source': hadith_id,
                    'target': str(c['chain_indx'][j]),
                    'hadith_no':aldata['info'][index]['hadith_no'].strip(),
                    'book':aldata['info'][index]['source'].strip()

                })
                if str(cdata['info'][index]['chain_indx'][j]) in getindex:
                    hadith_id = str(c['chain_indx'][j])
                j+=1
                print(hadith_id)
    with open('isnad/static/isnad/datasets/some_hadiths.json', 'w') as outfile:
        json.dump(wdata, outfile)
    return redirect('isnad:isnad')


def getrawisload(request):
    ind=""
    wdata = {}
    with open('isnad/static/isnad/datasets/all_rawis.json') as json_file:
        rdata = json.load(json_file)
    for index,r in enumerate(rdata['info']):
         wdata[rdata['info'][index]['scholar_indx']]=index
    with open('isnad/static/isnad/datasets/getrawisindex.json', 'w') as outfile:
        json.dump(wdata, outfile)
    return redirect('isnad:isnad')



def load(request):
    wdata = {}
    wdata['info'] = []
    with open('all_hadiths_clean.json') as json_file:
        aldata = json.load(json_file)
    for a in aldata['info']:
        if (a['chain_indx']):
            wdata['nodes'].append({
                'hadith_id': a['hadith_id'],
                'chain_indx': a['chain_indx']
            })
        else:
            wdata['nodes'].append({
                'hadith_id': a['hadith_id'],
                'chain_indx':[]
            })

    with open('all_hadiths_chain.json', 'w') as outfile:
        json.dump(wdata, outfile)
    return redirect('isnad:isnad')

isnad/templates/isnad/graph.html
<!DOCTYPE html>
<meta charset="utf-7">

<svg width="960" height="600"></svg>

<script src="https://d3js.org/d3.v4.min.js"></script>
<script>
var baseNodes = [
  { id: "1", group: 0, label: "আব্বাদ ইবন শারাহীল (রাঃ)", level: 1 },
  { id: "2"   , group: 0, label: "আলী ইবনু আবদুর রহমান মু'আবী (রহঃ)"   , level: 2 },
  { id: "3"   , group: 0, label: "আলা ইবনে যিয়াদ (রহঃ)"   , level: 2 },
  { id: "4"   , group: 0, label: "আ‘মাশ (রহঃ)"  , level: 2 },
  { id: "5"   , group: 0, label: "আ'রাজ (রহঃ)"    , level: 2 },
  { id: "6", group: 1, label: "আবায়া ইবনু রিফা‘আহ (রহঃ)", level: 1 },
  { id: "7"   , group: 1, label: "আবদে রাব্বিহী ইবন সাঈদ (রহঃ)"   , level: 2 },
  { id: "8"   , group: 1, label: "আবান ইবন উসমান (রহঃ)"   , level: 2 },
  { id: "9"  , group: 2, label: "আবদু খায়ের (রহঃ)"   , level: 1 },
  { id: "10"  , group: 2, label: "আব্দুল আ’লা (রহঃ)"   , level: 2 },
  { id: "11"  , group: 2, label: "আব্বাদ ইবনু তামীম (রহঃ)"  , level: 2 }
]

var baseLinks = [
	{ target: "1", source: "2" , strength: 0.7 },
	{ target: "1", source: "3" , strength: 0.7 },
  { target: "1", source: "4" , strength: 0.7 },
  { target: "1", source: "5" , strength: 0.7 },
  { target: "6", source: "7" , strength: 0.7 },
  { target: "6", source: "8" , strength: 0.7 },
  { target: "9"  , source: "10", strength: 0.7 },
  { target: "9"  , source: "11", strength: 0.7 },
  { target: "3"   , source: "5" , strength: 0.1 },
  { target: "10"  , source: "7" , strength: 0.1 },
  { target: "5"   , source: "8" , strength: 0.1 },
  { target: "2"   , source: "3" , strength: 0.1 },
  { target: "4"   , source: "7" , strength: 0.1 },
	{ target: "11"  , source: "3" , strength: 0.1 }
]

var nodes = [...baseNodes]
var links = [...baseLinks]

function getNeighbors(node) {
  return baseLinks.reduce(function (neighbors, link) {
      if (link.target.id === node.id) {
        neighbors.push(link.source.id)
      } else if (link.source.id === node.id) {
        neighbors.push(link.target.id)
      }
      return neighbors
    },
    [node.id]
  )
}

function isNeighborLink(node, link) {
  return link.target.id === node.id || link.source.id === node.id
}


function getNodeColor(node, neighbors) {
  if (Array.isArray(neighbors) && neighbors.indexOf(node.id) > -1) {
    return node.level === 1 ? 'blue' : 'green'
  }

  return node.level === 1 ? 'red' : 'gray'
}


function getLinkColor(node, link) {
  return isNeighborLink(node, link) ? 'green' : '#E5E5E5'
}

function getTextColor(node, neighbors) {
  return Array.isArray(neighbors) && neighbors.indexOf(node.id) > -1 ? 'green' : 'black'
}

var width = window.innerWidth
var height = window.innerHeight

var svg = d3.select('svg')
svg.attr('width', width).attr('height', height)

var linkElements,
  nodeElements,
  textElements

// we use svg groups to logically group the elements together
var linkGroup = svg.append('g').attr('class', 'links')
var nodeGroup = svg.append('g').attr('class', 'nodes')
var textGroup = svg.append('g').attr('class', 'texts')

// we use this reference to select/deselect
// after clicking the same element twice
var selectedId

// simulation setup with all forces
var linkForce = d3
  .forceLink()
  .id(function (link) { return link.id })
  .strength(function (link) { return link.strength })

var simulation = d3
  .forceSimulation()
  .force('link', linkForce)
  .force('charge', d3.forceManyBody().strength(-120))
  .force('center', d3.forceCenter(width / 2, height / 2))

var dragDrop = d3.drag().on('start', function (node) {
  node.fx = node.x
  node.fy = node.y
}).on('drag', function (node) {
  simulation.alphaTarget(0.7).restart()
  node.fx = d3.event.x
  node.fy = d3.event.y
}).on('end', function (node) {
  if (!d3.event.active) {
    simulation.alphaTarget(0)
  }
  node.fx = null
  node.fy = null
})

// select node is called on every click
// we either update the data according to the selection
// or reset the data if the same node is clicked twice
function selectNode(selectedNode) {
  if (selectedId === selectedNode.id) {
    selectedId = undefined
    resetData()
    updateSimulation()
  } else {
    selectedId = selectedNode.id
    updateData(selectedNode)
    updateSimulation()
  }

  var neighbors = getNeighbors(selectedNode)

  // we modify the styles to highlight selected nodes
  nodeElements.attr('fill', function (node) { return getNodeColor(node, neighbors) })
  textElements.attr('fill', function (node) { return getTextColor(node, neighbors) })
  linkElements.attr('stroke', function (link) { return getLinkColor(selectedNode, link) })
}

// this helper simple adds all nodes and links
// that are missing, to recreate the initial state
function resetData() {
  var nodeIds = nodes.map(function (node) { return node.id })

  baseNodes.forEach(function (node) {
    if (nodeIds.indexOf(node.id) === -1) {
      nodes.push(node)
    }
  })

  links = baseLinks
}

// diffing and mutating the data
function updateData(selectedNode) {
  var neighbors = getNeighbors(selectedNode)
  var newNodes = baseNodes.filter(function (node) {
    return neighbors.indexOf(node.id) > -1 || node.level === 1
  })

  var diff = {
    removed: nodes.filter(function (node) { return newNodes.indexOf(node) === -1 }),
    added: newNodes.filter(function (node) { return nodes.indexOf(node) === -1 })
  }

  diff.removed.forEach(function (node) { nodes.splice(nodes.indexOf(node), 1) })
  diff.added.forEach(function (node) { nodes.push(node) })

  links = baseLinks.filter(function (link) {
    return link.target.id === selectedNode.id || link.source.id === selectedNode.id
  })
}

function updateGraph() {
  // links
  linkElements = linkGroup.selectAll('line')
    .data(links, function (link) {
      return link.target.id + link.source.id
    })

  linkElements.exit().remove()

  var linkEnter = linkElements
    .enter().append('line')
    .attr('stroke-width', 1)
    .attr('stroke', 'rgba(50, 50, 50, 0.2)')

  linkElements = linkEnter.merge(linkElements)

  // nodes
  nodeElements = nodeGroup.selectAll('circle')
    .data(nodes, function (node) { return node.id })

  nodeElements.exit().remove()

  var nodeEnter = nodeElements
    .enter()
    .append('circle')
    .attr('r', 10)
    .attr('fill', function (node) { return node.level === 1 ? 'red' : 'gray' })
    .call(dragDrop)
    // we link the selectNode method here
    // to update the graph on every click
    .on('click', selectNode)

  nodeElements = nodeEnter.merge(nodeElements)

  // texts
  textElements = textGroup.selectAll('text')
    .data(nodes, function (node) { return node.id })

  textElements.exit().remove()

  var textEnter = textElements
    .enter()
    .append('text')
    .text(function (node) { return node.label })
    .attr('font-size', 15)
    .attr('dx', 15)
    .attr('dy', 4)

  textElements = textEnter.merge(textElements)
}

function updateSimulation() {
  updateGraph()

  simulation.nodes(nodes).on('tick', () => {
    nodeElements
      .attr('cx', function (node) { return node.x })
      .attr('cy', function (node) { return node.y })
    textElements
      .attr('x', function (node) { return node.x })
      .attr('y', function (node) { return node.y })
    linkElements
      .attr('x1', function (link) { return link.source.x })
      .attr('y1', function (link) { return link.source.y })
      .attr('x2', function (link) { return link.target.x })
      .attr('y2', function (link) { return link.target.y })
  })

  simulation.force('link').links(links)
  simulation.alphaTarget(0.7).restart()
}

// last but not least, we call updateSimulation
// to trigger the initial render
updateSimulation()

</script>

isnad/templates/isnad/graph3.html
{% load static %}
<head>
  <style> body { margin: 0; } </style>

  <script src="https://unpkg.com/react@16/umd/react.production.min.js"></script>
  <script src="https://unpkg.com/react-dom@16/umd/react-dom.production.min.js"></script>
  <script src="https://unpkg.com/babel-standalone"></script>

  <script src="https://unpkg.com/react-force-graph-vr"></script>
  <!--<script src="../../src/packages/react-force-graph-vr/dist/react-force-graph-vr.js"></script>-->
</head>

<body>
  <div id="graph"></div>

  <script type="text/jsx">
    fetch('{% static 'isnad/datasets/some_rawis.json' %}').then(res => res.json()).then(data => {
      ReactDOM.render(
        <ForceGraphVR
          graphData={data}
        //  nodeLabel={node => `${node.user}: ${node.description}`}
          // nodeAutoColorBy="user"
          linkDirectionalParticles={1}
        />,
        document.getElementById('graph')
      );
    });
  </script>
</body>

isnad/templates/isnad/graph4.html
{% load static %}
<!DOCTYPE html>
<html lang='en'>
<head>
  <meta charset='utf-8'>
  <title>Loading spin.js in d3.js chart</title>
  <meta name='author' content='Sundar Singh | eesur.com'>

  <script src='http://d3js.org/d3.v3.min.js' charset='utf-8'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.0.1/spin.min.js'></script>

  <style>
  @import url(http://fonts.googleapis.com/css?family=Source+Code+Pro:400,600);
  body {
    font-family: "Source Code Pro", Consolas, monaco, monospace;
    font-size: 18px;
    line-height: 1.5;
    font-weight: 400;
  }
  </style>
</head>
<body>

<section id='chart'></section>

<script>

// config references
var chartConfig = {
    target : 'chart',
    data_url : '{% static 'isnad/datasets/some_hadiths.json' %}',
    width: 900,
    height: 450,
    val: 90
};

// loader settings
var opts = {
  lines: 9, // The number of lines to draw
  length: 9, // The length of each line
  width: 5, // The line thickness
  radius: 14, // The radius of the inner circle
  color: '#EE3124', // #rgb or #rrggbb or array of colors
  speed: 1.9, // Rounds per second
  trail: 40, // Afterglow percentage
  className: 'spinner', // The CSS class to assign to the spinner
};

var target = document.getElementById(chartConfig.target);

// callback function wrapped for loader in 'init' function
function init() {

    // trigger loader
    var spinner = new Spinner(opts).spin(target);

    // slow the json load intentionally, so we can see it every load
    setTimeout(function() {

        // load json data and trigger callback
        d3.json(chartConfig.data_url, function(data) {

            // stop spin.js loader
            spinner.stop();

            // instantiate chart within callback
          //  chart(data);

        });

    }, 1500);
}

init();

// function chart(data) {
//
//     // sample bar chart showing ancient name occurrences in SGGS
//
//     var w = chartConfig.width;
//     var h = chartConfig.height;
//
//     var xScale = d3.scale.linear()
//         .domain([0, d3.max(data, function(d) { return d.value; })])
//         .range([0, w-100]);
//
//     var canvas = d3.select('#' + chartConfig.target)
//         .append('svg')
//             .attr('width', w)
//             .attr('height', h);
//
//
//     var rects = canvas.selectAll('rect')
//         .data(data)
//         .enter()
//         .append('rect')
//             .attr('width', 0)
//             .attr('height', h/10 - 2)
//             .attr('y', function (d, i) { return i * 50; })
//             .attr('fill', '#FDBB30');
//
//
//     rects.transition()
//         .duration(1000)
//         .delay(100)
//         .ease('linear')
//         .attr('width', function (d) { return xScale(d.value); });
//
//     canvas.selectAll('text')
//           .data(data)
//           .enter()
//           .append('text')
//               .attr('y', function (d, i) { return (i * 50) +30; })
//               .attr('x', function (d) { return xScale(d.value) + 10; })
//               .attr('fill', '#130C0E')
//               .text(function (d) { return d.name; });
// }

</script>

</body>
</html>

isnad/templates/isnad/isnad.html
{% extends 'base.html' %}
{% load static %}

{% block spadof %}
{% endblock %}

{% block navbar %}
	{% include 'navbar3.html' %}
{% endblock %}

{% block later %}

<!-- categories section -->
	<section class="categories-section spad">
		<div class="container">
			<div class="section-title">
				<h2>Our Isnad Graphs</h2>
				<p>Hadith (an Arabic word) refers to the words and actions of Prophet Mohammed.
          Those collections of Hadiths have been transmitted through generations of Muslim scholars
           until they have been collected and written in big collections.
           The chain of narrators is a main area of study in Islamic scholarship
            because a single hadith may have multiple chains of narrators (that may or may not overlap). </p>
			</div>
			<div class="row">
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'isnad/img/scholar.jpeg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:sgraph' %}">
								<h5>  علماء المسلمين   </h5>
							</a>
							<p> Authentic Inter-linked graph of Muslim Scholars </p>
							<span>Muslim Scholars</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'isnad/img/scholar.jpeg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:igraph' %}">
								<h5> السند  </h5>
							</a>
							<p> Hadith text, translation  and interactive chain of narrators (isnad)  </p>
							<span>Sanad,the chain of narration</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/3.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:graph1' %}">
								<h5>graph1</h5>
							</a>
							<p>graph1</p>
							<span>Size: bad de pm</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:graph2' %}">
								<h5>graph2</h5>
							</a>
							<p>graph2</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:graph3' %}">
								<h5>VR mode: graph3</h5>
							</a>
							<p>for big graph</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:graph4' %}">
								<h5>graph4</h5>
							</a>
							<p>graph4</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:graph5' %}">
								<h5>graph5</h5>
							</a>
							<p>graph5</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:sload' %}">
								<h5>Load Scholars</h5>
							</a>
							<p>--Load scholar data to json file--</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
				<div class="col-lg-4 col-md-6">
					<div class="categorie-item">
						<div class="ci-thumb set-bg" data-setbg="{% static 'img/categories/5.jpg' %}"></div>
						<div class="ci-text">
							<a href="{% url 'isnad:iload' %}">
								<h5>Load Isnad</h5>
							</a>
							<p>--Load Isnad data to json file--</p>
							<span>Size: Unknown</span>
						</div>
					</div>
				</div>
				<!-- categorie -->
			</div>
		</div>
	</section>
	<!-- categories section end -->
{% endblock later %}